PostSys/Models/GuestZone.cs
namespace PostSys.Models
{
	public class GuestZone
	{
		public int Id { get; set; }
		public string Name { get; set; }

		public string GuestId { get; set; }
		public ApplicationUser Guest { get; set; }

		public int FacultyId { get; set; }
		public Faculty Faculty { get; set; }
	}
}

PostSys/Controllers/GuestZonesController.cs
using Microsoft.AspNet.Identity;
using PostSys.Models;
using PostSys.ViewModels;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;

namespace PostSys.Controllers
{
    public class GuestZonesController : Controller
    {
        private ApplicationDbContext _context;

        public GuestZonesController()
        {
            _context = new ApplicationDbContext();
        }

        [Authorize(Roles = "Marketing Manager")]
        public ActionResult ListGuest()
        {
            var listGuest = _context.GuestZones.Include(g => g.Guest).Include(f => f.Faculty).ToList();

            return View(listGuest);
        }

        [Authorize(Roles = "Marketing Manager")]
        [HttpGet]
        public ActionResult CreateGuest()
        {
            var role = (from r in _context.Roles where r.Name.Contains("Guest") select r)
                                                             .FirstOrDefault();
            var listGuest = _context.Users.Where(x => x.Roles.Select(y => y.RoleId)
                                          .Contains(role.Id))
                                          .ToList();

            var listFaculty = _context.Faculties.ToList();

            var dropDownListFaculty = new GuestFacultyViewModel
            {
                Faculties = listFaculty,
                Guests = listGuest
            };

            return View(dropDownListFaculty);
        }

        [Authorize(Roles = "Marketing Manager")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateGuest(GuestZone guestZone)
        {
            var isExistGuest = _context.GuestZones.Include(f => f.Faculty).Any(n => n.FacultyId == guestZone.FacultyId ||
                                                       n.GuestId == guestZone.GuestId);
            if (isExistGuest == true)
            {
                return View("~/Views/ErrorValidations/Exist.cshtml");
            }

            var newGuest = new GuestZone
            {
                Name = guestZone.Name,
                FacultyId = guestZone.FacultyId,
                GuestId = guestZone.GuestId
            };

            if (newGuest.GuestId == null || newGuest.Name == null)
            {
                return View("~/Views/ErrorValidations/Exist.cshtml");
            }

            _context.GuestZones.Add(newGuest);
            _context.SaveChanges();

            return RedirectToAction("ListGuest");
        }

        [Authorize(Roles = "Marketing Manager")]
        public ActionResult DeleteGuest(int id)
        {
            var guestInDb = _context.GuestZones.SingleOrDefault(i => i.Id == id);

            if (guestInDb == null)
            {
                return View("~/Views/ErrorValidations/Null.cshtml");
            }

            _context.GuestZones.Remove(guestInDb);
            _context.SaveChanges();

            return RedirectToAction("ListGuest");
        }

        [Authorize(Roles = "Guest")]
        public ActionResult GuestZoneFaculty()
        {
            var getListPublication = _context.Publications.ToList();
            var getStudent = _context.Users.ToList();

            var getUser = User.Identity.GetUserId();
            var getGuestInFacultyIds = _context.GuestZones.Where(m => m.GuestId == getUser)
                                                          .Include(f => f.Faculty)
                                                          .Include(u => u.Guest)
                                                          .Select(m => m.FacultyId)
                                                          .ToList();

            if(getGuestInFacultyIds.Count() == 0)
            {
                return View("~/Views/ErrorValidations/Null.cshtml");
            }

            var getGuestInFacultyId = getGuestInFacultyIds[0];
            

            var guestZoneFaculty = _context.Publications.Where(n => n.Post.Assignment.Course.Class.Faculty.Id == getGuestInFacultyId)
                                                        .Include(p => p.Post.Assignment.Course.Class.Faculty)
                                                        .ToList();

            return View(guestZoneFaculty);
        }

        [Authorize(Roles = "Guest")]
        public FileResult DownloadFile(Post post)
        {

            var getFileById = _context.Posts.SingleOrDefault(c => c.Id == post.Id);

            return File(getFileById.File, "file", getFileById.UrlFile);
        }
    }
}

PostSys/Views/GuestZones/CreateGuest.cshtml
@model PostSys.ViewModels.GuestFacultyViewModel

@{
	ViewBag.Title = "CreateGuest";
}

@using Microsoft.AspNet.Identity

@if (Request.IsAuthenticated && User.IsInRole("Marketing Manager"))
{
	<!DOCTYPE html>
	<html lang="en">
	<head>
		<title>Create Guest</title>
		<!-- HTML5 Shim and Respond.js IE11 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 11]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
			<![endif]-->
		<!-- Meta -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />

		<!-- Favicon  -->
		<link rel="icon" href="~/images/customer - logo.png">
		<!-- fontawesome icon -->
		<link rel="stylesheet" href="~/assets/fonts/fontawesome/css/fontawesome-all.min.css">
		<!-- animation css -->
		<link rel="stylesheet" href="~/assets/plugins/animation/css/animate.min.css">
		<!-- vendor css -->
		<link rel="stylesheet" href="~/assets/css/style.css">
	</head>

	<body>
		<!-- [ Animate ] start -->
		<div class="loader-bg">
			<div class="loader-track">
				<div class="loader-fill"></div>
			</div>
		</div>
		<!-- [ Animate ] End -->
		<!-- Preloader -->
		<div class="spinner-wrapper">
			<div class="spinner">
				<div class="bounce1"></div>
				<div class="bounce2"></div>
				<div class="bounce3"></div>
			</div>
		</div>
		<!-- end of preloader -->
		<!-- [ navigation menu ] start -->
		<nav class="pcoded-navbar">
			<div class="navbar-wrapper">
				<div class="navbar-brand header-logo">
					<a href="~/Home/Index" class="b-brand">
						<div class="b-bg">
							<i class="feather icon-circle"></i>
						</div>
						<span class="b-title">CMS</span>
					</a>
					<a class="mobile-menu" id="mobile-collapse" href="javascript:"><span></span></a>
				</div>
				<div class="navbar-content scroll-div">
					<ul class="nav pcoded-inner-navbar">
						<li>
							<a href="~/Home/Index" class="nav-link "><span class="pcoded-micon"><i class="feather icon-home"></i></span><span class="pcoded-mtext">Home Page</span></a>
						</li>
						<li class="nav-item pcoded-menu-caption">
							<label>Marketing Manager Features</label>
						</li>

						<li class="nav-item pcoded-hasmenu">
							<a href="#!" class="nav-link "><span class="pcoded-micon"><i class="feather icon-clipboard"></i></span><span class="pcoded-mtext">Manage</span></a>
							<ul class="pcoded-submenu">
								<li>
									<a href="~/Faculties/CreateFaculty" class="nav-link "><span class="pcoded-mtext">Create Faculties</span></a>
								</li>
								<li>
									<a href="~/Classes/CreateClass" class="nav-link "><span class="pcoded-mtext">Create Classes</span></a>
								</li>
								<li>
									<a href="~/GuestZones/CreateGuest" class="nav-link "><span class="pcoded-mtext">Create Guests</span></a>
								</li>
							</ul>
						</li>
						<li class="nav-item pcoded-hasmenu">
							<a href="#!" class="nav-link "><span class="pcoded-micon"><i class="feather icon-clipboard"></i></span><span class="pcoded-mtext">List</span></a>
							<ul class="pcoded-submenu">
								<li>
									<a href="~/GuestZones/ListGuest" class="nav-link "><span class="pcoded-mtext">List Guests</span></a>
								</li>
								<li>
									<a href="~/Faculties/ListFaculty" class="nav-link "><span class="pcoded-mtext">List Faculties</span></a>
								</li>
								<li>
									<a href="~/Classes/ListClasses" class="nav-link "><span class="pcoded-mtext">List Classes</span></a>
								</li>
								<li>
									<a href="~/Courses/ListCourses" class="nav-link "><span class="pcoded-mtext">List Courses</span></a>
								</li>
								<li>
									<a href="~/Assignments/ListAssignment" class="nav-link "><span class="pcoded-mtext">List Assignments</span></a>
								</li>
								<li>
									<a href="~/Posts/ListPost" class="nav-link "><span class="pcoded-mtext">List Posts</span></a>
								</li>
								<li>
									<a href="~/Posts/ListComment" class="nav-link "><span class="pcoded-mtext">List Comments</span></a>
								</li>
								<li>
									<a href="~/Posts/ListPublication" class="nav-link "><span class="pcoded-mtext">List Publications</span></a>
								</li>
								<li>
									<a href="~/Deadlines/ListDeadline" class="nav-link "><span class="pcoded-mtext">List Deadlines</span></a>
								</li>
							</ul>
						</li>
						<li>
							<a href="~/Dashboards/Index" class="nav-link "><span class="pcoded-micon"><i class="feather icon-bar-chart"></i></span><span class="pcoded-mtext">Charts</span></a>
						</li>
						<li>
							<a href="~/Posts/DownloadZip" class="nav-link "><span class="pcoded-micon"><i class="feather icon-download"></i></span><span class="pcoded-mtext">Download File (Zip)</span></a>
						</li>
					</ul>
					<ul class="nav pcoded-inner-navbar">
						<li class="nav-item pcoded-menu-caption">
							<label>Login as: Marketing Manager</label>
						</li>
						<li>
							<a href="~/Home/Index" class="nav-link"><span class="pcoded-micon"><i class="feather icon-user"></i></span><span class="pcoded-mtext">@Html.DisplayName("Hello " + User.Identity.GetUserName() + "!")</span></a>
						</li>
						@using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "nav pcoded-inner-navbar" }))
						{

							<li>
								@Html.AntiForgeryToken()
								<a href="javascript:document.getElementById('logoutForm').submit()" class="nav-link"><span class="pcoded-micon"><i class="feather icon-log-out"></i></span><span class="pcoded-mtext">Log Out</span></a>
							</li>
						}
					</ul>
				</div>
			</div>
		</nav>
		<!-- [ navigation menu ] end -->
		<!-- [ Header ] start -->
		<header class="navbar pcoded-header navbar-expand-lg navbar-light">
			<div class="m-header">
				<a class="mobile-menu" id="mobile-collapse1" href="javascript:"><span></span></a>
				<a href="~/Home/Index" class="b-brand">
					<div class="b-bg">
						<i class="feather icon-circle"></i>
					</div>
					<span class="b-title">CMS</span>
				</a>
			</div>
			<a class="mobile-menu" id="mobile-header" href="javascript:">
				<i class="feather icon-more-horizontal"></i>
			</a>
			<div class="collapse navbar-collapse">
				<ul class="navbar-nav mr-auto">
					<li><a href="javascript:" class="full-screen" onclick="javascript:toggleFullScreen()"><i class="feather icon-maximize"></i></a></li>
				</ul>
			</div>
		</header>
		<!-- [ Header ] end -->
		<!-- [ Main Content ] start -->
		<div class="pcoded-main-container">
			<div class="pcoded-wrapper">
				<div class="pcoded-content">
					<div class="pcoded-inner-content">
						<div class="pcoded-inner-content">
							<!-- [ breadcrumb ] start -->
							<div class="page-header">
								<div class="page-block">
									<div class="row align-items-center">
										<div class="col-md-12">
											<div class="page-header-title">
												<h5 class="m-b-10">@Html.DisplayName("Welcome,  " + User.Identity.GetUserName() + "!")</h5>
											</div>
											<ul class="breadcrumb">
												<li class="breadcrumb-item"><a href="~/Home/Index"><i class="feather icon-home"></i></a></li>
												<li class="breadcrumb-item"><a href="javascript:">Create Guest</a></li>
											</ul>
										</div>
									</div>
								</div>
							</div>
							<!-- [ breadcrumb ] end -->
							<!-- [ Main Content ] start -->
							<div class="row">
								<div class="col-xl-12">
									<div class="card" style="max-width:40%; margin: 0 auto; float:none; margin-bottom:10px;">
										<div class="card-header">
											<h5>Create Guest</h5>
										</div>
										<div class="card-block table-border-style" style="margin: 0 auto; float:none; margin-bottom:10px;">
											@using (Html.BeginForm("CreateGuest", "GuestZones", FormMethod.Post))
											{
												@Html.AntiForgeryToken()

												<div class="form-group">
													@Html.LabelFor(p => p.GuestZone.Name)
													@Html.TextBoxFor(p => p.GuestZone.Name, new { @class = "form-control" })
													@Html.ValidationMessageFor(p => p.GuestZone.Name, "", new { @class = "text-danger" })
												</div>
												<div class="form-group">
													@Html.LabelFor(m => m.GuestZone.GuestId)
													@Html.DropDownListFor(m => m.GuestZone.GuestId,
														new SelectList(Model.Guests, "Id", "UserName"), "Select Guest",
														new { @class = "form-control" }
													)
												</div>

												<div class="form-group">
													@Html.LabelFor(m => m.GuestZone.FacultyId)
													@Html.DropDownListFor(m => m.GuestZone.FacultyId,
														new SelectList(Model.Faculties, "Id", "Name"), "Select Faculty",
														new { @class = "form-control" }
													)
												</div>

												<center><button type="submit" class="btn btn-primary">Assign more</button></center>

											}

											<!-- [ Main Content ] end -->
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

		<!-- [ Main Content ] end -->
		<!-- Required Js -->
		<script src="~/assets/js/vendor-all.min.js"></script>
		<script src="~/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
		<script src="~/assets/js/pcoded.min.js"></script>
	</body>
</html>
}

PostSys/Views/GuestZones/GuestZoneFaculty.cshtml
@model IEnumerable<PostSys.Models.Publication>
@{
	ViewBag.Title = "GuestZoneFaculty";
}

@using Microsoft.AspNet.Identity

@if (Request.IsAuthenticated)
{
	<!DOCTYPE html>
	<html lang="en">
	<head>
		<title>Guest Zone</title>
		<!-- HTML5 Shim and Respond.js IE11 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 11]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
			<![endif]-->
		<!-- Meta -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />

		<!-- Favicon  -->
		<link rel="icon" href="~/images/customer - logo.png">
		<!-- fontawesome icon -->
		<link rel="stylesheet" href="~/assets/fonts/fontawesome/css/fontawesome-all.min.css">
		<!-- animation css -->
		<link rel="stylesheet" href="~/assets/plugins/animation/css/animate.min.css">
		<!-- vendor css -->
		<link rel="stylesheet" href="~/assets/css/style.css">
	</head>

    <body>
        <!-- [ Animate ] start -->
        <div class="loader-bg">
            <div class="loader-track">
                <div class="loader-fill"></div>
            </div>
        </div>
        <!-- [ Animate ] End -->
        <!-- Preloader -->
        <div class="spinner-wrapper">
            <div class="spinner">
                <div class="bounce1"></div>
                <div class="bounce2"></div>
                <div class="bounce3"></div>
            </div>
        </div>
        <!-- end of preloader -->
        <!-- [ navigation menu ] start -->
        <nav class="pcoded-navbar">
            <div class="navbar-wrapper">
                <div class="navbar-brand header-logo">
                    <a href="~/Home/Index" class="b-brand">
                        <div class="b-bg">
                            <i class="feather icon-circle"></i>
                        </div>
                        <span class="b-title">CMS</span>
                    </a>
                    <a class="mobile-menu" id="mobile-collapse" href="javascript:"><span></span></a>
                </div>
                @if (Request.IsAuthenticated && User.IsInRole("Guest"))
                {
                    <div class="navbar-content scroll-div">
                        <ul class="nav pcoded-inner-navbar">
                            <li>
                                <a href="~/Home/Index" class="nav-link "><span class="pcoded-micon"><i class="feather icon-home"></i></span><span class="pcoded-mtext">Home Page</span></a>
                            </li>
                            <li class="nav-item pcoded-menu-caption">
                                <label>Function's Guest</label>
                            </li>
                            <li>
                                <a href="~/GuestZones/GuestZoneFaculty" class="nav-link "><span class="pcoded-micon"><i class="feather icon-user"></i></span><span class="pcoded-mtext">Guest's Faculties</span></a>
                            </li>
                        </ul>

                        <ul class="nav pcoded-inner-navbar">
                            <li class="nav-item pcoded-menu-caption">
                                <label>Login as: Guest</label>
                            </li>
                            <li>
                                <a href="~/Home/Index" class="nav-link"><span class="pcoded-micon"><i class="feather icon-user"></i></span><span class="pcoded-mtext">@Html.DisplayName("Hello " + User.Identity.GetUserName() + "!")</span></a>
                            </li>
                            @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "nav pcoded-inner-navbar" }))
                            {

                                <li>
                                    @Html.AntiForgeryToken()
                                    <a href="javascript:document.getElementById('logoutForm').submit()" class="nav-link"><span class="pcoded-micon"><i class="feather icon-log-out"></i></span><span class="pcoded-mtext">Log Out</span></a>
                                </li>
                            }
                        </ul>
                    </div>
                }
            </div>
        </nav>
        <!-- [ navigation menu ] end -->
        <!-- [ Header ] start -->
        <header class="navbar pcoded-header navbar-expand-lg navbar-light">
            <div class="m-header">
                <a class="mobile-menu" id="mobile-collapse1" href="javascript:"><span></span></a>
                <a href="~/Home/Index" class="b-brand">
                    <div class="b-bg">
                        <i class="feather icon-circle"></i>
                    </div>
                    <span class="b-title">CMS</span>
                </a>
            </div>
            <a class="mobile-menu" id="mobile-header" href="javascript:">
                <i class="feather icon-more-horizontal"></i>
            </a>
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav mr-auto">
                    <li><a href="javascript:" class="full-screen" onclick="javascript:toggleFullScreen()"><i class="feather icon-maximize"></i></a></li>
                </ul>
            </div>
        </header>
        <!-- [ Header ] end -->
        <!-- [ Main Content ] start -->
        <div class="pcoded-main-container">
            <div class="pcoded-wrapper">
                <div class="pcoded-content">
                    <div class="pcoded-inner-content">
                        <div class="pcoded-inner-content">
                            <!-- [ breadcrumb ] start -->
                            <div class="page-header">
                                <div class="page-block">
                                    <div class="row align-items-center">
                                        <div class="col-md-12">
                                            <div class="page-header-title">
                                                <h5 class="m-b-10">@Html.DisplayName("Welcome,  " + User.Identity.GetUserName() + "!")</h5>
                                            </div>
                                            <ul class="breadcrumb">
                                                <li class="breadcrumb-item"><a href="~/Home/Index"><i class="feather icon-home"></i></a></li>
                                                <li class="breadcrumb-item"><a href="javascript:">Guest's Faculties</a></li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- [ breadcrumb ] end -->
                            <!-- [ Main Content ] start -->
                            <div class="row">
                                <div class="col-xl-12">
                                    <div class="card">
                                        <div class="card-header">
                                            <h5> Guest's Faculties</h5>
                                        </div>
                                        <div class="card-block table-border-style">
                                            @using (Html.BeginForm("GuestZoneFaculty", "GuestZones", FormMethod.Post))
                                            {
                                                <div class="swiper-container-no-flexbox" >
                                                    <div class="row">
                                                        @foreach (var item in Model)
                                                        {
                                                            <div class="col-md-6 col-lg-4">
                                                                <div class="card" style="border-radius:10%">
                                                                    <img src="https://www.pxwall.com/wp-content/uploads/2018/06/Wallpaper%20Plane,%20minimalism,%20colors,%204K,%20Art%20373835076.jpg" alt="Lamp" style="border-radius:5%">
                                                                    <div class="card-body" style="border-radius:10%">
                                                                        <center><h4>@item.Post.Name</h4></center>
                                                                        <br />
                                                                        <h6>Student Name: @item.Post.Assignment.Course.Student.UserName</h6>
                                                                        <br />
                                                                        <h6>Faculty Name: @item.Post.Assignment.Course.Class.Faculty.Name</h6>
                                                                    </div>
                                                                    <div class="card-footer">
                                                                        <center> <button class="btn btn-glow-success">@Html.ActionLink("Download", "DownloadFile", new { id = item.PostId })</button></center>

                                                                    </div>
                                                                </div>
                                                            </div>
                                                        }

                                                        <!-- [ Main Content ] end -->
                                                    </div>
                                                </div>
                                            }
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>


            <!-- [ Main Content ] end -->
            <!-- Required Js -->
            <script src="~/assets/js/vendor-all.min.js"></script>
            <script src="~/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
            <script src="~/assets/js/pcoded.min.js"></script>
        </body>
</html>
}