PostSys/Controllers/ClassesController.cs
using PostSys.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using PostSys.ViewModels;
using Microsoft.AspNet.Identity;

namespace PostSys.Controllers
{
	public class ClassesController : Controller
	{
		private ApplicationDbContext _context;

		public ClassesController()
		{
			_context = new ApplicationDbContext();
		}

		// GET: Classes
		[Authorize(Roles = "Marketing Manager, Student")]
		public ActionResult ListClasses()
		{
			var getFaculies = _context.Faculties.ToList();
			var getCoordinator = _context.Users.ToList();

			var getClasses = _context.Classes.Include(f => f.Faculty).Include(c => c.Coordinator).ToList();

			return View(getClasses);
		}

		[Authorize(Roles = "Marketing Manager")]
		[HttpGet]
		public ActionResult CreateClass()
		{
			var role = (from r in _context.Roles where r.Name.Contains("Marketing Coordinator") select r)
															 .FirstOrDefault();
			var listCoordinator = _context.Users.Where(x => x.Roles.Select(y => y.RoleId)
									  .Contains(role.Id))
									  .ToList();

			var listFaculty = _context.Faculties.ToList();

			var dropDownListCoordinatorFaculty = new CoordinatorFacultyViewModel
			{
				Faculties = listFaculty,
				Coordinators = listCoordinator,
			};

			return View(dropDownListCoordinatorFaculty);
		}

		[Authorize(Roles = "Marketing Manager")]
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult CreateClass(Class @class)
		{
			var isExistClass = _context.Classes.Any(n => n.Name == @class.Name || 
													n.CoordinatorId == @class.CoordinatorId || 
													n.FacultyId == @class.FacultyId);
			if(isExistClass == true)
			{
				return View("~/Views/ErrorValidations/Exist.cshtml");
			}

			var newClass = new Class
			{
				Name = @class.Name,
				FacultyId = @class.FacultyId,
				CoordinatorId = @class.CoordinatorId,
				EnrollmentKey = @class.EnrollmentKey
			};

			if (newClass.CoordinatorId == null || newClass.EnrollmentKey == null || newClass.Name == null)
			{
				return View("~/Views/ErrorValidations/Null.cshtml");
			}

			_context.Classes.Add(newClass);
			_context.SaveChanges();
			
			return RedirectToAction("ListClasses");
		}

		[Authorize(Roles = "Marketing Manager")]
		[HttpGet]
		public ActionResult DeleteClass(int id)
		{
			var classInDb = _context.Classes.SingleOrDefault(i => i.Id == id);

			if(classInDb == null)
			{
				return View("~/Views/ErrorValidations/Null.cshtml");
			}

			_context.Classes.Remove(classInDb);
			_context.SaveChanges();

			return RedirectToAction("ListClasses");
		}


		[Authorize(Roles = "Student")]
		public ActionResult AssignClass()
		{
			return View();
		}

		[Authorize(Roles = "Student")]
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult AssignClass(Course course, int id)
		{
			var classId = _context.Classes.SingleOrDefault(i => i.Id == id);
			var currentStudent = User.Identity.GetUserId();

			//get EnrollmentKey from ClassId
			var classIds = _context.Classes.Where(m => m.Id == id)
				                           .Select(m => m.EnrollmentKey)
										   .ToList();
			var enrollKey = classIds[0];
			var enrollKeyLength = enrollKey.Length;

			//get FacultyName from ClassId
			var facultyNames = _context.Classes.Where(m => m.Id == id)
											   .Include(f => f.Faculty)
											   .Select(m => m.Faculty.Name)
											   .ToList();
			var facultyName = facultyNames[0];

			var checkIsExist = _context.Courses.Where(m => m.StudentId == currentStudent)
				                               .Select(m => m.StudentId)
										       .FirstOrDefault();

			var newAssign = new Course
			{
				Name = facultyName + "_" + "Course",
				ClassId = classId.Id,
				StudentId = currentStudent,
				EnrollmentKey = course.EnrollmentKey
			};

			if(newAssign.EnrollmentKey == null)
			{
				return View("~/Views/ErrorValidations/Null.cshtml");
			}
			
			if(newAssign.StudentId == checkIsExist)
			{
				return View("~/Views/ErrorValidations/Exist.cshtml");
			}

			if (newAssign.EnrollmentKey.Contains(enrollKey) && newAssign.EnrollmentKey.Length == enrollKeyLength)
			{
				_context.Courses.Add(newAssign);
				_context.SaveChanges();

				return RedirectToAction("ListClasses");
			}

			return View("~/Views/ErrorValidations/Null.cshtml");
		}

		[Authorize(Roles = "Marketing Coordinator")]
		public ActionResult ManageMyClass()
		{
			var getCurrentUser = User.Identity.GetUserName();

			var getMyClass = _context.Classes.Where(c => c.Coordinator.UserName == getCurrentUser).Include(f => f.Faculty).ToList();

			return View(getMyClass);
		}
	}
}

PostSys/Views/Classes/AssignClass.cshtml
@model PostSys.Models.Course
@{
	ViewBag.Title = "AssignClass";
}





@using Microsoft.AspNet.Identity
@if (Request.IsAuthenticated && User.IsInRole("Student"))
{
	<!DOCTYPE html>
	<html lang="en">
	<head>
		<title>Assign Class</title>
		<!-- HTML5 Shim and Respond.js IE11 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 11]>
		<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
		<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->
		<!-- Meta -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />

		<!-- Favicon  -->
		<link rel="icon" href="~/images/customer - logo.png">
		<!-- fontawesome icon -->
		<link rel="stylesheet" href="~/assets/fonts/fontawesome/css/fontawesome-all.min.css">
		<!-- animation css -->
		<link rel="stylesheet" href="~/assets/plugins/animation/css/animate.min.css">
		<!-- vendor css -->
		<link rel="stylesheet" href="~/assets/css/style.css">
		<link rel='stylesheet' href='https://cdn.rawgit.com/t4t5/sweetalert/v0.2.0/lib/sweet-alert.css'>

	</head>

	<body>
		<!-- [ Animate ] start -->
		<div class="loader-bg">
			<div class="loader-track">
				<div class="loader-fill"></div>
			</div>
		</div>
		<!-- [ Animate ] End -->
		<!-- Preloader -->
		<div class="spinner-wrapper">
			<div class="spinner">
				<div class="bounce1"></div>
				<div class="bounce2"></div>
				<div class="bounce3"></div>
			</div>
		</div>
		<!-- end of preloader -->
		<!-- [ navigation menu ] start -->
		<nav class="pcoded-navbar">
			<div class="navbar-wrapper">
				<div class="navbar-brand header-logo">
					<a href="~/Home/Index" class="b-brand">
						<div class="b-bg">
							<i class="feather icon-circle"></i>
						</div>
						<span class="b-title">CMS</span>
					</a>
					<a class="mobile-menu" id="mobile-collapse" href="javascript:"><span></span></a>
				</div>
				<div class="navbar-content scroll-div">
					<ul class="nav pcoded-inner-navbar">
						<li>
							<a href="~/Home/Index" class="nav-link "><span class="pcoded-micon"><i class="feather icon-home"></i></span><span class="pcoded-mtext">Home Page</span></a>
						</li>
						<li class="nav-item pcoded-menu-caption">
							<label>Student Features</label>
						</li>


						<li class="">
							<a href="~/Classes/ListClasses" class="nav-link "><span class="pcoded-micon"><i class="feather icon-user-plus"></i></span><span class="pcoded-mtext">List Classes</span></a>
						</li>

						<li class="nav-item pcoded-hasmenu">
							<a href="#!" class="nav-link "><span class="pcoded-micon"><i class="feather icon-clipboard"></i></span><span class="pcoded-mtext">Manage</span></a>
							<ul class="pcoded-submenu">
								<li class="">
									<a href="~/Courses/ManageMyCourse" class="nav-link "><span class="pcoded-mtext">Manage My Course</span></a>
								</li>
								<li class="">
									<a href="~/Assignments/ManageMyAssignment" class="nav-link "><span class="pcoded-mtext">Manage My Assignment</span></a>
								</li>
								<li class="">
									<a href="~/Posts/ManageMyPost" class="nav-link "><span class="pcoded-mtext">Manage My Post</span></a>
								</li>

							</ul>
						</li>
					</ul>
					<ul class="nav pcoded-inner-navbar">
						<li class="nav-item pcoded-menu-caption">
							<label>Login as: Student</label>
						</li>
						<li>
							<a href="~/Home/Index" class="nav-link"><span class="pcoded-micon"><i class="feather icon-user"></i></span><span class="pcoded-mtext">@Html.DisplayName("Hello " + User.Identity.GetUserName() + "!")</span></a>
						</li>
						@using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "nav pcoded-inner-navbar" }))
						{

							<li>
								@Html.AntiForgeryToken()
								<a href="javascript:document.getElementById('logoutForm').submit()" class="nav-link"><span class="pcoded-micon"><i class="feather icon-log-out"></i></span><span class="pcoded-mtext">Log Out</span></a>
							</li>
						}
					</ul>
				</div>
			</div>
		</nav>
		<!-- [ navigation menu ] end -->
		<!-- [ Header ] start -->
		<header class="navbar pcoded-header navbar-expand-lg navbar-light">
			<div class="m-header">
				<a class="mobile-menu" id="mobile-collapse1" href="javascript:"><span></span></a>
				<a href="~/Home/Index" class="b-brand">
					<div class="b-bg">
						<i class="feather icon-circle"></i>
					</div>
					<span class="b-title">CMS</span>
				</a>
			</div>
			<a class="mobile-menu" id="mobile-header" href="javascript:">
				<i class="feather icon-more-horizontal"></i>
			</a>
			<div class="collapse navbar-collapse">
				<ul class="navbar-nav mr-auto">
					<li><a href="javascript:" class="full-screen" onclick="javascript:toggleFullScreen()"><i class="feather icon-maximize"></i></a></li>
				</ul>

			</div>
		</header>
		<!-- [ Header ] end -->
		<!-- [ Main Content ] start -->
		<div class="pcoded-main-container">
			<div class="pcoded-wrapper">
				<div class="pcoded-content">
					<div class="pcoded-inner-content">
						<div class="pcoded-inner-content">
							<!-- [ breadcrumb ] start -->
							<div class="page-header">
								<div class="page-block">
									<div class="row align-items-center">
										<div class="col-md-12">
											<div class="page-header-title">
												<h5 class="m-b-10">@Html.DisplayName("Welcome,  " + User.Identity.GetUserName() + "!")</h5>
											</div>
											<ul class="breadcrumb">
												<li class="breadcrumb-item"><a href="~/Home/Index"><i class="feather icon-home"></i></a></li>
												<li class="breadcrumb-item"><a href="~/Classes/ListClasses">List Classes</a></li>
												<li class="breadcrumb-item"><a href="javascript:">Assign to Class</a></li>
											</ul>
										</div>
									</div>
								</div>
							</div>
							<!-- [ breadcrumb ] end -->
							<!-- [ Main Content ] start -->
							<div class="row">
								<div class="col-xl-12">
									<div class="card" style="max-width:40%; margin: 0 auto; float:none; margin-bottom:10px;">
										<div class="card-header">
											<h5> Assign Class</h5>
										</div>
										<div class="card-block table-border-style" style="margin: 0 auto; float:none; margin-bottom:10px;">
											@using (Html.BeginForm("AssignClass", "Classes", FormMethod.Post))
											{
												@Html.AntiForgeryToken()

												<div class="form-group">
													@Html.LabelFor(p => p.EnrollmentKey)
													@Html.PasswordFor(p => p.EnrollmentKey, new { @class = "form-control" })
													@Html.ValidationMessageFor(p => p.EnrollmentKey, "", new { @class = "text-danger" })
												</div>

												<button type="submit" class="btn btn-primary">Assign</button>

												<script src='https://cdn.rawgit.com/t4t5/sweetalert/v0.2.0/lib/sweet-alert.min.js'></script>

												@*<script>
													document.getElementById('sweetalert').onclick = function () {
														swal("Success!", "You have successfully assigned!", "success");
													};
												</script>*@
											}
											<!-- [ Main Content ] end -->
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

		<!-- [ Main Content ] end -->
		<!-- Required Js -->
		<script src="~/assets/js/vendor-all.min.js"></script>
		<script src="~/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
		<script src="~/assets/js/pcoded.min.js"></script>
	</body>
</html>
}             

PostSys/Views/Classes/CreateClass.cshtml
@model PostSys.ViewModels.CoordinatorFacultyViewModel
@{
	ViewBag.Title = "CreateClass";
}

@using Microsoft.AspNet.Identity


@if (Request.IsAuthenticated && User.IsInRole("Marketing Manager"))
{
	<!DOCTYPE html>
	<html lang="en">
	<head>
		<title>Create Class</title>
		<!-- HTML5 Shim and Respond.js IE11 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 11]>
		<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
		<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->
		<!-- Meta -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />

		<!-- Favicon  -->
		<link rel="icon" href="~/images/customer - logo.png">
		<!-- fontawesome icon -->
		<link rel="stylesheet" href="~/assets/fonts/fontawesome/css/fontawesome-all.min.css">
		<!-- animation css -->
		<link rel="stylesheet" href="~/assets/plugins/animation/css/animate.min.css">
		<!-- vendor css -->
		<link rel="stylesheet" href="~/assets/css/style.css">
		<link rel='stylesheet' href='https://cdn.rawgit.com/t4t5/sweetalert/v0.2.0/lib/sweet-alert.css'>

	</head>

	<body>
		<!-- [ Animate ] start -->
		<div class="loader-bg">
			<div class="loader-track">
				<div class="loader-fill"></div>
			</div>
		</div>
		<!-- [ Animate ] End -->
		<!-- Preloader -->
		<div class="spinner-wrapper">
			<div class="spinner">
				<div class="bounce1"></div>
				<div class="bounce2"></div>
				<div class="bounce3"></div>
			</div>
		</div>
		<!-- end of preloader -->
		<!-- [ navigation menu ] start -->
		<nav class="pcoded-navbar">
			<div class="navbar-wrapper">
				<div class="navbar-brand header-logo">
					<a href="~/Home/Index" class="b-brand">
						<div class="b-bg">
							<i class="feather icon-circle"></i>
						</div>
						<span class="b-title">CMS</span>
					</a>
					<a class="mobile-menu" id="mobile-collapse" href="javascript:"><span></span></a>
				</div>
				<div class="navbar-content scroll-div">
					<ul class="nav pcoded-inner-navbar">
						<li>
							<a href="~/Home/Index" class="nav-link "><span class="pcoded-micon"><i class="feather icon-home"></i></span><span class="pcoded-mtext">Home Page</span></a>
						</li>
						<li class="nav-item pcoded-menu-caption">
							<label>Marketing Manager Features</label>
						</li>

						<li class="nav-item pcoded-hasmenu">
							<a href="#!" class="nav-link "><span class="pcoded-micon"><i class="feather icon-clipboard"></i></span><span class="pcoded-mtext">Manage</span></a>
							<ul class="pcoded-submenu">
								<li>
									<a href="~/Faculties/CreateFaculty" class="nav-link "><span class="pcoded-mtext">Create Faculties</span></a>
								</li>
								<li>
									<a href="~/Classes/CreateClass" class="nav-link "><span class="pcoded-mtext">Create Classes</span></a>
								</li>
								<li>
									<a href="~/GuestZones/CreateGuest" class="nav-link "><span class="pcoded-mtext">Create Guests</span></a>
								</li>
							</ul>
						</li>
						<li class="nav-item pcoded-hasmenu">
							<a href="#!" class="nav-link "><span class="pcoded-micon"><i class="feather icon-clipboard"></i></span><span class="pcoded-mtext">List</span></a>
							<ul class="pcoded-submenu">
								<li>
									<a href="~/GuestZones/ListGuest" class="nav-link "><span class="pcoded-mtext">List Guests</span></a>
								</li>
								<li>
									<a href="~/Faculties/ListFaculty" class="nav-link "><span class="pcoded-mtext">List Faculties</span></a>
								</li>
								<li>
									<a href="~/Classes/ListClasses" class="nav-link "><span class="pcoded-mtext">List Classes</span></a>
								</li>
								<li>
									<a href="~/Courses/ListCourses" class="nav-link "><span class="pcoded-mtext">List Courses</span></a>
								</li>
								<li>
									<a href="~/Assignments/ListAssignment" class="nav-link "><span class="pcoded-mtext">List Assignments</span></a>
								</li>
								<li>
									<a href="~/Posts/ListPost" class="nav-link "><span class="pcoded-mtext">List Posts</span></a>
								</li>
								<li>
									<a href="~/Posts/ListComment" class="nav-link "><span class="pcoded-mtext">List Comments</span></a>
								</li>
								<li>
									<a href="~/Posts/ListPublication" class="nav-link "><span class="pcoded-mtext">List Publications</span></a>
								</li>
								<li>
									<a href="~/Deadlines/ListDeadline" class="nav-link "><span class="pcoded-mtext">List Deadlines</span></a>
								</li>
							</ul>
						</li>
						<li>
							<a href="~/Dashboards/Index" class="nav-link "><span class="pcoded-micon"><i class="feather icon-bar-chart"></i></span><span class="pcoded-mtext">Charts</span></a>
						</li>
						<li>
							<a href="~/Posts/DownloadZip" class="nav-link "><span class="pcoded-micon"><i class="feather icon-download"></i></span><span class="pcoded-mtext">Download File (Zip)</span></a>
						</li>
					</ul>
					<ul class="nav pcoded-inner-navbar">
						<li class="nav-item pcoded-menu-caption">
							<label>Login as: Marketing Manager</label>
						</li>
						<li>
							<a href="~/Home/Index" class="nav-link"><span class="pcoded-micon"><i class="feather icon-user"></i></span><span class="pcoded-mtext">@Html.DisplayName("Hello " + User.Identity.GetUserName() + "!")</span></a>
						</li>
						@using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "nav pcoded-inner-navbar" }))
						{

							<li>
								@Html.AntiForgeryToken()
								<a href="javascript:document.getElementById('logoutForm').submit()" class="nav-link"><span class="pcoded-micon"><i class="feather icon-log-out"></i></span><span class="pcoded-mtext">Log Out</span></a>
							</li>
						}
					</ul>
				</div>
			</div>
		</nav>
		<!-- [ navigation menu ] end -->
		<!-- [ Header ] start -->
		<header class="navbar pcoded-header navbar-expand-lg navbar-light">
			<div class="m-header">
				<a class="mobile-menu" id="mobile-collapse1" href="javascript:"><span></span></a>
				<a href="~/Home/Index" class="b-brand">
					<div class="b-bg">
						<i class="feather icon-circle"></i>
					</div>
					<span class="b-title">CMS</span>
				</a>
			</div>
			<a class="mobile-menu" id="mobile-header" href="javascript:">
				<i class="feather icon-more-horizontal"></i>
			</a>
			<div class="collapse navbar-collapse">
				<ul class="navbar-nav mr-auto">
					<li><a href="javascript:" class="full-screen" onclick="javascript:toggleFullScreen()"><i class="feather icon-maximize"></i></a></li>
				</ul>
			</div>
		</header>
		<!-- [ Header ] end -->
		<!-- [ Main Content ] start -->
		<div class="pcoded-main-container">
			<div class="pcoded-wrapper">
				<div class="pcoded-content">
					<div class="pcoded-inner-content">
						<div class="pcoded-inner-content">
							<!-- [ breadcrumb ] start -->
							<div class="page-header">
								<div class="page-block">
									<div class="row align-items-center">
										<div class="col-md-12">
											<div class="page-header-title">
												<h5 class="m-b-10">@Html.DisplayName("Welcome,  " + User.Identity.GetUserName() + "!")</h5>
											</div>
											<ul class="breadcrumb">
												<li class="breadcrumb-item"><a href="~/Home/Index"><i class="feather icon-home"></i></a></li>
												<li class="breadcrumb-item"><a href="javascript:">Create Classes</a></li>
											</ul>
										</div>
									</div>
								</div>
							</div>
							<!-- [ breadcrumb ] end -->
							<!-- [ Main Content ] start -->
							<div class="row">
								<div class="col-xl-12">
									<div class="card" style="max-width:40%; margin: 0 auto; float:none; margin-bottom:10px;">
										<div class="card-header">
											<h5> Create Classes</h5>
										</div>
										<div class="card-block table-border-style" style="margin: 0 auto; float:none; margin-bottom:10px;">
											@using (Html.BeginForm("CreateClass", "Classes", FormMethod.Post))
											{
												@Html.AntiForgeryToken()
												<div class="form-group">
													@Html.LabelFor(p => p.Class.Name)
													@Html.TextBoxFor(p => p.Class.Name, new { @class = "form-control" })
													@Html.ValidationMessageFor(p => p.Class.Name, "", new { @class = "text-danger" })
												</div>

												<div class="form-group">
													@Html.LabelFor(m => m.Class.CoordinatorId)
													@Html.DropDownListFor(m => m.Class.CoordinatorId,
														new SelectList(Model.Coordinators, "Id", "UserName"), "Select Coordinator",
														new { @class = "form-control" }
													)
												</div>

												<div class="form-group">
													@Html.LabelFor(m => m.Class.FacultyId)
													@Html.DropDownListFor(m => m.Class.FacultyId,
														new SelectList(Model.Faculties, "Id", "Name"), "Select Faculty",
														new { @class = "form-control" }
													)
												</div>

												<div class="form-group">
													@Html.LabelFor(p => p.Class.EnrollmentKey)
													@Html.PasswordFor(p => p.Class.EnrollmentKey, new { @class = "form-control" })
													@Html.ValidationMessageFor(p => p.Class.EnrollmentKey, "", new { @class = "text-danger" })
												</div>

												<center><button id="sweetalert" type="submit" class="btn btn-primary">Create</button></center>

												<script src='https://cdn.rawgit.com/t4t5/sweetalert/v0.2.0/lib/sweet-alert.min.js'></script>

												<script>
													document.getElementById('sweetalert').onclick = function () {
														swal("Created!", "You have successfully created!", "success");
													};
												</script>
											}
											<!-- [ Main Content ] end -->
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

		<!-- [ Main Content ] end -->
		<!-- Required Js -->
		<script src="~/assets/js/vendor-all.min.js"></script>
		<script src="~/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
		<script src="~/assets/js/pcoded.min.js"></script>
	</body>
</html>
}